version: '3'
services:
  db:
    build: ./docker/database/
    environment:
      - POSTGRES_DB=sentry
    volumes:
      - ./.data:/var/lib/postgresql/data
  redis:
    image: redis:3.2
    command: redis-server --appendonly yes
    volumes:
      - ./.data:/data
    ports:
      - "6379:6379"
  web:
    build: .
    command: python manage.py serve -r
    volumes:
      - .:/opt/sentry
    ports:
      - "8686:8686"
    depends_on:
      - db
      - redis
  frontend:
    build: ./frontend/
    environment:
      - NODE_ENV=docker
    command: npm run serve
    volumes:
      - ./frontend:/opt/frontend
      - /opt/frontend/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - web
  bot:
    build: .
    command: python manage.py bot -e docker
    volumes:
      - .:/opt/sentry
    ports:
      - "7171:7171"
    depends_on:
      - web
  workers:
    build: .
    command: python manage.py workers
    volumes:
      - .:/opt/sentry
    depends_on:
      - web